/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lenovo
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        //userstable.setBackground(new Color(0,0,0,0));
        //((DefaultTableCellRenderer)userstable.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        //userstable.setOpaque(false);
        //((DefaultTableCellRenderer)userstable.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        userstable.setGridColor(Color.WHITE);
        userstable.setVisible(false);
        jScrollPane1.setVisible(false);
        label.setVisible(false);
        textfield.setVisible(false);
        errorlabel.setVisible(false);
        button.setVisible(false);
    }
    
    public void fetch(){
        PreparedStatement ps = null;
        ResultSet rs = null;
        String selectquery = null;
        if(tablecb.getSelectedIndex() == 0)
            selectquery = "SELECT * FROM users";
            
        try{
            ps = MyConnection.getConnection().prepareStatement(selectquery);
            rs = ps.executeQuery();
            userstable.setModel(DbUtils.resultSetToTableModel(rs));
                
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void delete(){
        String email = textfield.getText();
        PreparedStatement ps;
        ResultSet rs;
        String deletequery = "DELETE FROM users WHERE Emailid like ?";
        String selectquery = "SELECT Contactno FROM users WHERE Emailid like ?";
            
        try{
            ps = MyConnection.getConnection().prepareStatement(selectquery);
            ps.setString(1, email);
            rs = ps.executeQuery();
            if(rs.next())
            {
                ps = MyConnection.getConnection().prepareStatement(deletequery);
                ps.setString(1, email);
                ps.executeUpdate();
                fetch();
            }
            else
                errorlabel.setText("Invalid Data");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        errorlabel = new javax.swing.JLabel();
        selecttablelabel = new javax.swing.JLabel();
        tablecb = new javax.swing.JComboBox();
        optionbutton = new javax.swing.JButton();
        button = new javax.swing.JButton();
        selectoptionlabel = new javax.swing.JLabel();
        textfield = new javax.swing.JTextField();
        viewtablebutton = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        optioncb = new javax.swing.JComboBox();
        logoutbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userstable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Have Heart One", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome admin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 40));

        errorlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        errorlabel.setForeground(new java.awt.Color(255, 102, 102));
        errorlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(errorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, 30));

        selecttablelabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        selecttablelabel.setForeground(new java.awt.Color(204, 204, 204));
        selecttablelabel.setText("Select your table");
        jPanel1.add(selecttablelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 30));

        tablecb.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        tablecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Users" }));
        tablecb.setOpaque(false);
        jPanel1.add(tablecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 30));

        optionbutton.setFont(new java.awt.Font("HelveticaNeue", 0, 18)); // NOI18N
        optionbutton.setText("»");
        optionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(optionbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 40, 30));

        button.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        button.setText("Delete");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 130, 30));

        selectoptionlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        selectoptionlabel.setForeground(new java.awt.Color(204, 204, 204));
        selectoptionlabel.setText("Select your option");
        jPanel1.add(selectoptionlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 30));

        textfield.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        jPanel1.add(textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 30));

        viewtablebutton.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        viewtablebutton.setText("View Table");
        viewtablebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewtablebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(viewtablebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, 30));

        label.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        label.setForeground(new java.awt.Color(204, 204, 204));
        label.setText("Enter email id");
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 30));

        optioncb.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        optioncb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delete user", "Update Price" }));
        optioncb.setOpaque(false);
        jPanel1.add(optioncb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 30));

        logoutbutton.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 450));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userstable.setBackground(new java.awt.Color(51, 51, 51));
        userstable.setForeground(new java.awt.Color(255, 255, 255));
        userstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userstable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(userstable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 570, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewtablebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewtablebuttonActionPerformed
        // TODO add your handling code here:
        userstable.setVisible(true);
        jScrollPane1.setVisible(true);
        fetch();
    }//GEN-LAST:event_viewtablebuttonActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        if(optioncb.getSelectedIndex() == 0)
        {
            delete();
        }
        else
        {
            //update();
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void optionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionbuttonActionPerformed
        // TODO add your handling code here:
        if(optioncb.getSelectedIndex() == 0)
        {
            label.setVisible(true);
            textfield.setVisible(true);
            errorlabel.setVisible(true);
            button.setVisible(true);
            label.setText("Enter email id");
            button.setText("Delete");
        }
        else if(optioncb.getSelectedIndex() == 1)
        {
            label.setVisible(true);
            textfield.setVisible(true);
            errorlabel.setVisible(true);
            button.setVisible(true);
            label.setText("Enter data to be changed");
            button.setText("Update");
        }
    }//GEN-LAST:event_optionbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel errorlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton optionbutton;
    private javax.swing.JComboBox optioncb;
    private javax.swing.JLabel selectoptionlabel;
    private javax.swing.JLabel selecttablelabel;
    private javax.swing.JComboBox tablecb;
    private javax.swing.JTextField textfield;
    private javax.swing.JTable userstable;
    private javax.swing.JButton viewtablebutton;
    // End of variables declaration//GEN-END:variables
}
