/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Login extends JFrame {

    /**
     * Creates new form Login
     */

    public Login() {
        initComponents();
    }

    public String MD5(String password) throws NoSuchAlgorithmException{
        MessageDigest md5 = MessageDigest.getInstance("MD5");
        md5.update(StandardCharsets.UTF_8.encode(password));
        return String.format("%032x", new BigInteger(1, md5.digest()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        quotelabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        hotelnamelabel = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        emailidlabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        emailidtext = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        emailidlabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        errorlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(97, 212, 195));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quotelabel.setFont(new java.awt.Font("HelveticaNeue", 0, 18)); // NOI18N
        quotelabel.setForeground(new java.awt.Color(255, 255, 255));
        quotelabel.setText("Not all those who wander are lost");
        sidepanel.add(quotelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 232, 265, -1));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 256, 12));

        hotelnamelabel.setFont(new java.awt.Font("Have Heart One", 0, 48)); // NOI18N
        hotelnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        hotelnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelnamelabel.setText("The Wanderer's Nest");
        hotelnamelabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sidepanel.add(hotelnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 151, 260, 60));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 450));

        mainpanel.setBackground(new java.awt.Color(36, 47, 65));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailidlabel.setFont(new java.awt.Font("Have Heart One", 0, 36)); // NOI18N
        emailidlabel.setForeground(new java.awt.Color(204, 204, 204));
        emailidlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailidlabel.setText("Welcome, Wanderer!");
        mainpanel.add(emailidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 330, 40));

        passwordlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 16)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordlabel.setText("Password");
        mainpanel.add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 90, 31));

        emailidtext.setBackground(new java.awt.Color(36, 47, 65));
        emailidtext.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        emailidtext.setForeground(new java.awt.Color(204, 204, 204));
        emailidtext.setText("Enter email id");
        emailidtext.setBorder(null);
        emailidtext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailidtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailidtextFocusGained(evt);
            }
        });
        emailidtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailidtextMouseClicked(evt);
            }
        });
        mainpanel.add(emailidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 350, 30));

        password.setBackground(new java.awt.Color(36, 47, 65));
        password.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        mainpanel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 350, -1));
        mainpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 330, 10));
        mainpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 330, 10));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("New Wanderer?");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 140, 40));

        emailidlabel1.setFont(new java.awt.Font("HelveticaNeue", 0, 16)); // NOI18N
        emailidlabel1.setForeground(new java.awt.Color(204, 204, 204));
        emailidlabel1.setText("Email Id");
        mainpanel.add(emailidlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 31));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        jButton2.setText("Login");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 140, 40));

        errorlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 12)); // NOI18N
        errorlabel.setForeground(new java.awt.Color(255, 51, 51));
        errorlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mainpanel.add(errorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 220, 20));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 460, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailidtextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailidtextMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailidtextMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void emailidtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailidtextFocusGained
        // TODO add your handling code here:
        emailidtext.setText("");
    }//GEN-LAST:event_emailidtextFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String userpassword = null;
        String pass = String.valueOf(password.getPassword());
        if(emailidtext.getText().equals("Enter email id") || "".equals(pass) || "".equals(emailidtext.getText()))
            errorlabel.setText("Email id or password empty");
        else if(emailidtext.getText().equals("admin") && pass.equals("admin"))
        {
            new AdminPage().setVisible(true);
            this.dispose();
        }
        else
        {
            boolean usernameexists = false;
            String email = emailidtext.getText();
            try {
                userpassword = MD5(pass);
            } 
            catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement ps;
            String query = "SELECT Emailid, Password FROM users WHERE Emailid like ?";
            
            try{
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, email);
                ResultSet rs = ps.executeQuery();
                if(rs.next())
                {
                    usernameexists = true;
                    String dbemail = rs.getString("Emailid");
                    String dbpassword = rs.getString("Password");
                    if(userpassword.equals(dbpassword))
                    {
                        new Search(dbemail).setVisible(true);
                        this.dispose();
                    }
                    else
                        errorlabel.setText("Invalid email id or password");
                }
                else
                    errorlabel.setText("Invalid email id or password");
            } 
            catch (SQLException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //new Search().setVisible(true);
        //this.dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new NewUser().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailidlabel;
    private javax.swing.JLabel emailidlabel1;
    private javax.swing.JTextField emailidtext;
    private javax.swing.JLabel errorlabel;
    private javax.swing.JLabel hotelnamelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JLabel quotelabel;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
