/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }
    
    public String MD5(String password) throws NoSuchAlgorithmException{
        MessageDigest md5 = MessageDigest.getInstance("MD5");
        md5.update(StandardCharsets.UTF_8.encode(password));
        return String.format("%032x", new BigInteger(1, md5.digest()));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        headerpanel = new javax.swing.JPanel();
        greetinglabel = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        lnamelabel = new javax.swing.JLabel();
        emailtext = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        emaillabel = new javax.swing.JLabel();
        salutationlabel = new javax.swing.JLabel();
        lnametext = new javax.swing.JTextField();
        fnametext = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        contactlabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        contacttext = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        passwordfield = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        signupbutton = new javax.swing.JButton();
        fnamelabel = new javax.swing.JLabel();
        salutationcb = new javax.swing.JComboBox();
        lnameerror = new javax.swing.JLabel();
        contacterror = new javax.swing.JLabel();
        tcerrorlabel = new javax.swing.JLabel();
        fnameerror = new javax.swing.JLabel();
        passworderror = new javax.swing.JLabel();
        emailerror = new javax.swing.JLabel();
        tccheckbox = new javax.swing.JCheckBox();
        privacylabel = new javax.swing.JLabel();
        errorlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(36, 47, 65));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Have Heart One", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("The Wanderer's Nest");
        sidepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, 40));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 450));

        headerpanel.setBackground(new java.awt.Color(97, 212, 195));
        headerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetinglabel.setFont(new java.awt.Font("Have Heart One", 0, 36)); // NOI18N
        greetinglabel.setForeground(new java.awt.Color(255, 255, 255));
        greetinglabel.setText("Become a wanderer!");
        headerpanel.add(greetinglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 40));

        getContentPane().add(headerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 60));

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnamelabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        lnamelabel.setText("Last Name");
        lnamelabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainpanel.add(lnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, 30));

        emailtext.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        emailtext.setText("Enter your email address");
        emailtext.setBorder(null);
        emailtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtextFocusLost(evt);
            }
        });
        emailtext.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                emailtextInputMethodTextChanged(evt);
            }
        });
        emailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtextActionPerformed(evt);
            }
        });
        mainpanel.add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 300, 30));
        mainpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 300, 10));

        emaillabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        emaillabel.setText("Email-id");
        emaillabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainpanel.add(emaillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 120, 30));

        salutationlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        salutationlabel.setText("Salutation");
        salutationlabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainpanel.add(salutationlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 30));

        lnametext.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        lnametext.setText("Enter your last name");
        lnametext.setBorder(null);
        lnametext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnametextFocusGained(evt);
            }
        });
        lnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametextActionPerformed(evt);
            }
        });
        mainpanel.add(lnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 300, 30));

        fnametext.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        fnametext.setText("Enter your first name");
        fnametext.setBorder(null);
        fnametext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnametextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnametextFocusLost(evt);
            }
        });
        fnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametextActionPerformed(evt);
            }
        });
        mainpanel.add(fnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 300, 30));
        mainpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 300, 10));
        mainpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 300, 10));

        contactlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        contactlabel.setText("Contact Number");
        contactlabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainpanel.add(contactlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, 30));

        passwordlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        passwordlabel.setText("Password");
        passwordlabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainpanel.add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 120, 30));

        contacttext.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        contacttext.setText("Enter your contact number");
        contacttext.setBorder(null);
        contacttext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contacttextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contacttextFocusLost(evt);
            }
        });
        contacttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttextActionPerformed(evt);
            }
        });
        mainpanel.add(contacttext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 300, 30));
        mainpanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 300, 10));
        mainpanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 300, 10));

        passwordfield.setBorder(null);
        passwordfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfieldFocusGained(evt);
            }
        });
        mainpanel.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 300, 30));

        jButton1.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        jButton1.setText("Already a wanderer? Sign in here");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        signupbutton.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        signupbutton.setText("Sign up");
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        mainpanel.add(signupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 130, 40));

        fnamelabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        fnamelabel.setText("First Name");
        fnamelabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainpanel.add(fnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, 30));

        salutationcb.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        salutationcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr", "Ms", "Mrs" }));
        mainpanel.add(salutationcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 70, 30));

        lnameerror.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        lnameerror.setForeground(new java.awt.Color(255, 51, 51));
        lnameerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainpanel.add(lnameerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 40, 30));

        contacterror.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        contacterror.setForeground(new java.awt.Color(255, 51, 51));
        contacterror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainpanel.add(contacterror, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 40, 30));

        tcerrorlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        tcerrorlabel.setForeground(new java.awt.Color(255, 51, 51));
        tcerrorlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mainpanel.add(tcerrorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 200, 30));

        fnameerror.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        fnameerror.setForeground(new java.awt.Color(255, 51, 51));
        fnameerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainpanel.add(fnameerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 40, 30));

        passworderror.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        passworderror.setForeground(new java.awt.Color(255, 51, 51));
        passworderror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainpanel.add(passworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 40, 30));

        emailerror.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        emailerror.setForeground(new java.awt.Color(255, 51, 51));
        emailerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainpanel.add(emailerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 40, 30));

        tccheckbox.setBackground(new java.awt.Color(255, 255, 255));
        tccheckbox.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        tccheckbox.setText("I accept all terms and conditions");
        tccheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tccheckboxActionPerformed(evt);
            }
        });
        mainpanel.add(tccheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 230, 30));

        privacylabel.setFont(new java.awt.Font("HelveticaNeue", 1, 14)); // NOI18N
        privacylabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        privacylabel.setText("Check our privacy policy");
        privacylabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                privacylabelMouseClicked(evt);
            }
        });
        mainpanel.add(privacylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 220, 30));

        errorlabel.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        errorlabel.setForeground(new java.awt.Color(255, 51, 51));
        errorlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mainpanel.add(errorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 300, 30));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 640, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtextActionPerformed

    private void lnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnametextActionPerformed

    private void fnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametextActionPerformed

    private void contacttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttextActionPerformed

    private void fnametextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnametextFocusGained
        // TODO add your handling code here:
        if(fnametext.getText().equals("Enter your first name"))
            fnametext.setText("");
    }//GEN-LAST:event_fnametextFocusGained

    private void lnametextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnametextFocusGained
        // TODO add your handling code here:
        if(lnametext.getText().equals("Enter your last name"))
            lnametext.setText("");
    }//GEN-LAST:event_lnametextFocusGained

    private void contacttextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contacttextFocusGained
        // TODO add your handling code here:
        if(contacttext.getText().equals("Enter your contact number"))
            contacttext.setText("");
    }//GEN-LAST:event_contacttextFocusGained

    private void emailtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtextFocusGained
        // TODO add your handling code here:
        if(emailtext.getText().equals("Enter your email address"))
            emailtext.setText("");
    }//GEN-LAST:event_emailtextFocusGained

    private void passwordfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusGained
        // TODO add your handling code here:
        passwordfield.setText("");
    }//GEN-LAST:event_passwordfieldFocusGained

    private void fnametextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnametextFocusLost
        // TODO add your handling code here:
        if(fnametext.getText().equals(""))
            fnametext.setText("Enter your first name");
        
    }//GEN-LAST:event_fnametextFocusLost

    private void emailtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtextFocusLost
        // TODO add your handling code here:
        if(emailtext.getText().equals(""))
            emailtext.setText("Enter your email address");
    }//GEN-LAST:event_emailtextFocusLost

    private void lnametextFocusLost(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        if(lnametext.getText().equals(""))
            lnametext.setText("Enter your last name");
    }     
    
    private void contacttextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contacttextFocusLost
        // TODO add your handling code here:
        if(contacttext.getText().equals(""))
            contacttext.setText("Enter contact number");
        else if(contacttext.getText().length() != 10)
            contacterror.setText("X");
        else
        {
            String contact = contacttext.getText();
            int i = 0, flag = 0;
            char[] cno = new char[10];
            cno = contact.toCharArray();
            while(i != 10)
            {
                if(cno[i] >= '0' && cno[i] <= '9')
                    i++;
                else
                {
                    flag = 1;
                    i++;
                }
            }
            if(flag == 0)
                contacterror.setText("");
            else
                contacterror.setText("X");
        }
    }//GEN-LAST:event_contacttextFocusLost

    private void emailtextInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_emailtextInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailtextInputMethodTextChanged

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        // TODO add your handling code here:
        
        if("Enter your first name".equals(fnametext.getText()))
            fnameerror.setText("X");
        if("Enter your last name".equals(lnametext.getText()))
            lnameerror.setText("X");
        if("Enter your contact number".equals(contacttext.getText()))
            contacterror.setText("X");
        if("Enter your email address".equals(emailtext.getText()))
            emailerror.setText("X");
        if("".equals(String.valueOf(passwordfield.getPassword())))
            passworderror.setText("X");
            
        if(tccheckbox.isSelected() == false)
            tcerrorlabel.setText("Please accept T&C");
        else
            tcerrorlabel.setText("");
        
        if(!"".equals(fnameerror.getText()) || !"".equals(lnameerror.getText()) || !"".equals(contacterror.getText()) || !"".equals(emailerror.getText()) || !"".equals(passworderror.getText()) || !"".equals(tcerrorlabel.getText()))
            errorlabel.setText("Please check your input(s)");           
        else
        {
            errorlabel.setText("");
            //To get salutation
            int sal = salutationcb.getSelectedIndex();
            String salutation = null;
            switch(sal)
            {
                case 0: salutation = "Mr"; break;
                case 1: salutation = "Ms"; break;
                case 2: salutation = "Mrs"; break;
            }
        
            //To get first name and last name and contact no
            String fname = fnametext.getText();
            String lname = lnametext.getText();
            String contact = contacttext.getText();
            long cno = Long.parseLong(contact);
        
            //To get email and password
            String email = emailtext.getText();
            String pass = String.valueOf(passwordfield.getPassword());
            String password = null;
            
            System.out.println(salutation + " " + fname + " " + lname);
            System.out.println(email);
            System.out.println(pass);
            
            //To convert to md5
            try {
                password = MD5(pass);
                System.out.println(password);
            } 
            catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //To insert into database
            PreparedStatement ps;
            String insertquery = "INSERT INTO Users VALUES (?,?,?,?,?,?)";
            
            try{
                ps = MyConnection.getConnection().prepareStatement(insertquery);
                
                ps.setString(1, salutation);
                ps.setString(2, fname);
                ps.setString(3, lname);
                ps.setLong(4, cno);
                ps.setString(5, email);
                ps.setString(6, password);
                
                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "Welcome " + salutation + " " + fname + " " + lname);
                    new Search(email).setVisible(true);
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //new Terms().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tccheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tccheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tccheckboxActionPerformed

    private void privacylabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privacylabelMouseClicked
        // TODO add your handling code here:
        new Terms().setVisible(true);
    }//GEN-LAST:event_privacylabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contacterror;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JTextField contacttext;
    private javax.swing.JLabel emailerror;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField emailtext;
    private javax.swing.JLabel errorlabel;
    private javax.swing.JLabel fnameerror;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JTextField fnametext;
    private javax.swing.JLabel greetinglabel;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lnameerror;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JTextField lnametext;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel passworderror;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JLabel privacylabel;
    private javax.swing.JComboBox salutationcb;
    private javax.swing.JLabel salutationlabel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JButton signupbutton;
    private javax.swing.JCheckBox tccheckbox;
    private javax.swing.JLabel tcerrorlabel;
    // End of variables declaration//GEN-END:variables
}
