/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ACE03
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form Payments
     */
    public void buttonenabler()
    {
        if(ErrorLB.getText().equals(""))
            ConfirmB.setEnabled(true);
        else
            ConfirmB.setEnabled(false);
    }
    
    public Payments() {
        initComponents();
        visalabel.setVisible(false);
        mastercardlabel.setVisible(false);
    }
    
    String destination, checkindate, checkoutdate;
    long days;
    int total;
    public Payments(String destination, long days, String checkindate, String checkoutdate, int total) {
        initComponents();
        this.destination = destination;
        this.days = days;
	this.total = total;
        this.checkindate = checkindate;
        this.checkoutdate = checkoutdate;
        if("Mumbai".equals(destination))
            AmountLB.setText("Rs "+total);
        else if("Dubai".equals(destination))
            AmountLB.setText("Rs "+(int)(19.83*total));
        else if("London".equals(destination))
            AmountLB.setText("Rs "+(int)(95.02*total));
        visalabel.setVisible(false);
        mastercardlabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardsBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        CreditRB = new javax.swing.JRadioButton();
        DebitRB = new javax.swing.JRadioButton();
        ChooseLB = new javax.swing.JLabel();
        VMCardLB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        HotelLB = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CVVTF = new javax.swing.JTextField();
        ExpDateLB = new javax.swing.JLabel();
        MonthCB = new javax.swing.JComboBox<>();
        YearCB = new javax.swing.JComboBox<>();
        NameoncardTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        PreB = new javax.swing.JButton();
        ConfirmB = new javax.swing.JButton();
        ErrorLB = new javax.swing.JLabel();
        CardNoTF = new javax.swing.JTextField();
        AmountLB = new javax.swing.JLabel();
        PayAMountLB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        visalabel = new javax.swing.JLabel();
        mastercardlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreditRB.setBackground(new java.awt.Color(36, 47, 65));
        CardsBG.add(CreditRB);
        CreditRB.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        CreditRB.setForeground(new java.awt.Color(204, 204, 204));
        CreditRB.setText("Credit Card");
        CreditRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditRBActionPerformed(evt);
            }
        });
        jPanel1.add(CreditRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        DebitRB.setBackground(new java.awt.Color(36, 47, 65));
        CardsBG.add(DebitRB);
        DebitRB.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        DebitRB.setForeground(new java.awt.Color(204, 204, 204));
        DebitRB.setText("Debit Card");
        DebitRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitRBActionPerformed(evt);
            }
        });
        jPanel1.add(DebitRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        ChooseLB.setBackground(new java.awt.Color(204, 204, 204));
        ChooseLB.setFont(new java.awt.Font("HelveticaNeue", 0, 18)); // NOI18N
        ChooseLB.setForeground(new java.awt.Color(204, 204, 204));
        ChooseLB.setText("Choose:");
        jPanel1.add(ChooseLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, -1));

        VMCardLB.setFont(new java.awt.Font("HelveticaNeue", 1, 12)); // NOI18N
        VMCardLB.setForeground(new java.awt.Color(255, 204, 0));
        VMCardLB.setText("    Visa /  MasterCard");
        jPanel1.add(VMCardLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 450));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HotelLB.setFont(new java.awt.Font("Have Heart One", 0, 48)); // NOI18N
        HotelLB.setForeground(new java.awt.Color(255, 255, 255));
        HotelLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HotelLB.setText("The Wanderer's Nest");
        jPanel2.add(HotelLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 14, 430, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 650, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BANKING PORTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 0, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CVVTF.setFont(new java.awt.Font("HelveticaNeue", 0, 15)); // NOI18N
        CVVTF.setText("CVV / CVC*");
        CVVTF.setBorder(null);
        CVVTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CVVTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CVVTFFocusLost(evt);
            }
        });
        CVVTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVTFActionPerformed(evt);
            }
        });
        jPanel3.add(CVVTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, -1));

        ExpDateLB.setFont(new java.awt.Font("HelveticaNeue", 0, 15)); // NOI18N
        ExpDateLB.setText("Expiration Date:");
        ExpDateLB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(ExpDateLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 140, 20));

        MonthCB.setFont(new java.awt.Font("HelveticaNeue", 0, 11)); // NOI18N
        MonthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        MonthCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthCBActionPerformed(evt);
            }
        });
        jPanel3.add(MonthCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        YearCB.setFont(new java.awt.Font("HelveticaNeue", 0, 11)); // NOI18N
        YearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038" }));
        YearCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearCBActionPerformed(evt);
            }
        });
        jPanel3.add(YearCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        NameoncardTF.setFont(new java.awt.Font("HelveticaNeue", 0, 15)); // NOI18N
        NameoncardTF.setText("Name On Card");
        NameoncardTF.setBorder(null);
        NameoncardTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameoncardTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameoncardTFFocusLost(evt);
            }
        });
        NameoncardTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameoncardTFMouseClicked(evt);
            }
        });
        NameoncardTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameoncardTFActionPerformed(evt);
            }
        });
        jPanel3.add(NameoncardTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 270, 10));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, 10));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 270, 20));

        PreB.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        PreB.setText("Previous");
        PreB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreBActionPerformed(evt);
            }
        });
        jPanel3.add(PreB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        ConfirmB.setFont(new java.awt.Font("HelveticaNeue", 0, 14)); // NOI18N
        ConfirmB.setText("Confirm");
        ConfirmB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfirmBMouseEntered(evt);
            }
        });
        ConfirmB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBActionPerformed(evt);
            }
        });
        jPanel3.add(ConfirmB, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        ErrorLB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ErrorLB.setForeground(new java.awt.Color(255, 0, 0));
        ErrorLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorLB.setToolTipText("");
        jPanel3.add(ErrorLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 270, 20));

        CardNoTF.setFont(new java.awt.Font("HelveticaNeue", 0, 15)); // NOI18N
        CardNoTF.setText("Card Number*");
        CardNoTF.setBorder(null);
        CardNoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CardNoTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CardNoTFFocusLost(evt);
            }
        });
        jPanel3.add(CardNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 220, -1));

        AmountLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AmountLB.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(AmountLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, 20));

        PayAMountLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PayAMountLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PayAMountLB.setText("Your Payment amount:");
        jPanel3.add(PayAMountLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Riyaz\\Desktop\\Merger\\Picture1.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 80, 60));

        visalabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Riyaz\\Desktop\\Merger\\visa.png")); // NOI18N
        visalabel.setText("jLabel2");
        jPanel3.add(visalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 80, 40));

        mastercardlabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Riyaz\\Desktop\\Merger\\Mastercard.png")); // NOI18N
        mastercardlabel.setText("jLabel2");
        jPanel3.add(mastercardlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 80, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 650, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreditRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditRBActionPerformed

    private void DebitRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DebitRBActionPerformed

    private void CVVTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVTFActionPerformed
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_CVVTFActionPerformed

    private void NameoncardTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameoncardTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameoncardTFActionPerformed

    private void MonthCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthCBActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_MonthCBActionPerformed

    private void YearCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearCBActionPerformed

    private void PreBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreBActionPerformed
        // TODO add your handling code here:
        new RoomSelection(destination,days,checkindate,checkoutdate).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PreBActionPerformed

    private void ConfirmBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBActionPerformed
        /*Date date = new Date();
        DateFormat sysm = new SimpleDateFormat("MM");
        DateFormat sysy = new SimpleDateFormat("yyyy");
        int sysmi = Integer.parseInt(sysm.format(date));
        int sysyi = Integer.parseInt(sysy.format(date));
        int expdm = MonthCB.getSelectedIndex();
        int expdy = YearCB.getSelectedIndex(); 
        if(expdm == 0 || expdy == 0)
        {
            ErrorLB.setText("Please recheck your details & insert again");
        }
        else if(sysyi > (expdy + 2017))
        {
            ErrorLB.setText("Please recheck your details & insert again");
        }
        else if(sysmi > expdm)
        {
            ErrorLB.setText("Please recheck your details & insert again");
        }
        else
        {
            ErrorLB.setText("");
        }
        
        if(ErrorLB.getText().equals(""))
        {
            ConfirmB.setEnabled(true);
        }
        else
        {
            ConfirmB.setEnabled(false);
        }*/
        
        
                    // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmBActionPerformed

    private void NameoncardTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameoncardTFMouseClicked
        if(NameoncardTF.getText().equals("Name On Card"))
            NameoncardTF.setText("");
        if(CardNoTF.getText().equals(""))
            CardNoTF.setText("Card Number*");
        if(CVVTF.getText().equals(""))
            CVVTF.setText("CVV / CVC*");
        // TODO add your handling code here:
    }//GEN-LAST:event_NameoncardTFMouseClicked

    private void CVVTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CVVTFFocusGained
        if(NameoncardTF.getText().equals(""))
            NameoncardTF.setText("Name On Card");
        if(CardNoTF.getText().equals(""))
            CardNoTF.setText("Card Number*");
        if(CVVTF.getText().equals("CVV / CVC*"))
            CVVTF.setText("");
                // TODO add your handling code here:
    }//GEN-LAST:event_CVVTFFocusGained

    private void NameoncardTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameoncardTFFocusGained
        if(NameoncardTF.getText().equals("Name On Card"))
            NameoncardTF.setText("");
        if(CardNoTF.getText().equals(""))
            CardNoTF.setText("Card Number*");
        if(CVVTF.getText().equals(""))
            CVVTF.setText("CVV / CVC*");// TODO add your handling code here:
    }//GEN-LAST:event_NameoncardTFFocusGained

    private void CVVTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CVVTFFocusLost
        String cvvstr = CVVTF.getText();
        //int cvvint = Integer.parseInt(cvvstr);
        if(cvvstr.matches("[0-9]+") && cvvstr.length() == 3)
        {
            ErrorLB.setText("");
            CVVTF.setText("***");
        }
        else
        {
            ErrorLB.setText("Please recheck your details & insert again");
            
        }
            
        /*   String cvvstr = CVVTF.getText();
        try
        {
            Integer.parseInt(cvvstr);
        }
        catch(NumberFormatException e)
        {
            ErrorLB.setText("Please recheck your details & insert again.");
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVTFFocusLost

    private void CardNoTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CardNoTFFocusGained

        if(NameoncardTF.getText().equals(""))
            NameoncardTF.setText("Name On Card");
        if(CardNoTF.getText().equals("Card Number*"))
            CardNoTF.setText("");
        if(CVVTF.getText().equals(""))
            CVVTF.setText("CVV / CVC*");
        String inputstr = CardNoTF.getText();
        char[] input = inputstr.toCharArray();
        if(input[0] == '4' || input[0] == '5') {}
        else
           CardNoTF.setText("");
            
        
            
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNoTFFocusGained

    private void CardNoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CardNoTFFocusLost

        ErrorLB.setText("");
        String input = CardNoTF.getText(), r = null;
        StringBuilder result = new StringBuilder();
        int x = 0, flag = 0;
        if(input.length() != 16 || input.matches("[a-zA-Z]+"))
        {
            ErrorLB.setText("Please recheck your details & insert again");
        }
        else if(input.length() == 16 && x == 0 )
        {
            for (int i = 0; i < input.length(); i++) {
                if (i % 4 == 0 && i != 0) {
                result.append("-");
                }

                result.append(input.charAt(i));
            }
            x = x + 1;
            r = result.toString();
            CardNoTF.setText(r);
            flag = 1;
        }
        if(flag == 1)
        {
            if("4".equals(r.substring(0,1)))
            {
                visalabel.setVisible(true);
                mastercardlabel.setVisible(false);
            }
            else if("5".equals(r.substring(0,1)))
            {
                mastercardlabel.setVisible(true);
                visalabel.setVisible(false);
            }
            else
            {
                mastercardlabel.setVisible(false);
                visalabel.setVisible(false);
            }
        }
        else
        {
            mastercardlabel.setVisible(false);
            visalabel.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNoTFFocusLost

    private void NameoncardTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameoncardTFFocusLost
        String nameoncardstr = NameoncardTF.getText();
        if(nameoncardstr.matches("[a-zA-Z]+") || nameoncardstr.contains(" "))
        {
            ErrorLB.setText("");
        }
        else
        {
            ErrorLB.setText("Please recheck your details & insert again");
        }
            
// TODO add your handling code here:
    }//GEN-LAST:event_NameoncardTFFocusLost

    private void ConfirmBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmBMouseEntered
        Date date = new Date();
        DateFormat sysm = new SimpleDateFormat("MM");
        DateFormat sysy = new SimpleDateFormat("yyyy");
        int sysmi = Integer.parseInt(sysm.format(date));
        int sysyi = Integer.parseInt(sysy.format(date));
        int expdm = MonthCB.getSelectedIndex();
        int expdy = YearCB.getSelectedIndex(); 
        if(expdm == 0 || expdy == 0)
        {
            ErrorLB.setText("Please recheck your details & insert again0");
        }
        else if(sysyi > (expdy + 2017))
        {
            ErrorLB.setText("Please recheck your details & insert againy");
        }
        else if(sysmi > expdm  && sysyi >= (expdy + 2017))
        {
            ErrorLB.setText("Please recheck your details & insert againm");
        }
        else
        {
            ErrorLB.setText("");
        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_ConfirmBMouseEntered
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Payments().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLB;
    private javax.swing.JTextField CVVTF;
    private javax.swing.JTextField CardNoTF;
    private javax.swing.ButtonGroup CardsBG;
    private javax.swing.JLabel ChooseLB;
    private javax.swing.JButton ConfirmB;
    private javax.swing.JRadioButton CreditRB;
    private javax.swing.JRadioButton DebitRB;
    private javax.swing.JLabel ErrorLB;
    private javax.swing.JLabel ExpDateLB;
    private javax.swing.JLabel HotelLB;
    private javax.swing.JComboBox<String> MonthCB;
    private javax.swing.JTextField NameoncardTF;
    private javax.swing.JLabel PayAMountLB;
    private javax.swing.JButton PreB;
    private javax.swing.JLabel VMCardLB;
    private javax.swing.JComboBox<String> YearCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel mastercardlabel;
    private javax.swing.JLabel visalabel;
    // End of variables declaration//GEN-END:variables
}
